# Generated by Django 4.2.30 on 2026-05-24 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название особенности')),
                ('icon', models.CharField(default='✨', max_length=8, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Особенности',
                'verbose_name_plural': 'Особенности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название района')),
                ('description', models.TextField(blank=True, verbose_name='Описание района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Район',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название достопримечательности')),
                ('category', models.CharField(choices=[('nature', 'Природный ландшафт'), ('culture', 'Исторический городок'), ('waterfall', 'Водопады и ущелья'), ('cave', 'Пещеры и карст'), ('ethnic', 'Этническая культура')], max_length=20, verbose_name='Тип достопримечательности')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('address', models.CharField(max_length=180, verbose_name='Адрес')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена билета')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг рекомендации')),
                ('opening_date', models.DateField(verbose_name='Дата открытия/создания')),
                ('is_world_heritage', models.BooleanField(default=False, verbose_name='Объект Всемирного наследия')),
                ('image_url', models.URLField(blank=True, verbose_name='Ссылка на изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('features', models.ManyToManyField(blank=True, related_name='spots', to='catalog.feature', verbose_name='Особенности')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='catalog.region', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательность',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_season', models.CharField(max_length=80, verbose_name='Лучший сезон для поездки')),
                ('suggested_hours', models.PositiveSmallIntegerField(default=3, verbose_name='Рекомендуемое время посещения, часы')),
                ('transport_tips', models.TextField(verbose_name='Советы по транспорту')),
                ('official_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон для справок')),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='catalog.scenicspot', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительная информация',
            },
        ),
    ]
